string location_name
string location_address
string action_name
string action_start_datetime
string action_success
int8    camera_num            #0 for front camera, 1 for arm camera
---
bool photo_request_submitted
